name: ctOS
version: '${project.version}'
main: com.ctos.CtOSPlugin
api-version: '1.21'
author: Zoeille
description: Dynamic synchronized traffic lights for Minecraft

dependencies:
  server:
    BKCommonLib:
      load: BEFORE
      required: true
    Train_Carts:
      load: BEFORE
      required: true

permissions:
  ctos.use:
    description: Allows using ctOS commands
    default: op
  ctos.wand:
    description: Allows using the setup wand
    default: op
  ctos.admin:
    description: Full ctOS administrative access
    default: op
    children:
      ctos.use: true
      ctos.wand: true
